apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel-container
          image: simple-devops-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000